name: binder_env
channels:
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=0.24.0=py36_0
  - backcall=0.1.0=py36_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.4.16=py36_0
  - cffi=1.11.5=py36h9745a5d_0
  - chardet=3.0.4=py36_1
  - cryptography=2.2.2=py36h14c3975_0
  - decorator=4.3.0=py36_0
  - idna=2.7=py36_0
  - intel-openmp=2018.0.0=8
  - ipykernel=4.8.2=py36_0
  - ipython=6.4.0=py36_0
  - ipython_genutils=0.2.0=py36hb52b0d5_0
  - jedi=0.12.0=py36_1
  - jupyter_client=5.2.3=py36_0
  - jupyter_core=4.4.0=py36h7c827e3_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - mkl=2018.0.2=1
  - mkl_fft=1.0.1=py36h3010b51_0
  - mkl_random=1.0.1=py36h629b387_0
  - ncurses=6.1=hf484d3e_0
  - numpy=1.14.2=py36hdbf6ddf_1
  - matplotlib=2.2.2=py36_1
  - openssl=1.0.2o=h20670df_0
  - pandas=0.22.0=py36hf484d3e_0
  - parso=0.2.0=py36_0
  - pexpect=4.5.0=py36_0
  - pickleshare=0.7.4=py36h63277f8_0
  - pip=10.0.1=py36_0
  - prompt_toolkit=1.0.15=py36h17d85b1_0
  - ptyprocess=0.5.2=py36h69acd42_0
  - pycparser=2.18=py36_1
  - pygments=2.2.0=py36h0d3125c_0
  - pyopenssl=18.0.0=py36_0
  - pysocks=1.6.8=py36_0
  - python=3.6.5=hc3d631a_2
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.4=py36_0
  - pyzmq=17.0.0=py36h14c3975_0
  - readline=7.0=ha6073c6_4
  - requests=2.19.1=py36_0
  - scipy=1.1.0=py36hfc37229_0
  - setuptools=39.1.0=py36_0
  - simplegeneric=0.8.1=py36_2
  - six=1.11.0=py36h372c433_1
  - sqlite=3.23.1=he433501_0
  - tk=8.6.7=hc745277_3
  - tornado=5.0.2=py36_0
  - traitlets=4.3.2=py36h674d592_0
  - urllib3=1.23=py36_0
  - wcwidth=0.1.7=py36hdf4376a_0
  - wheel=0.31.1=py36_0
  - xz=5.2.3=h5e939de_4
  - zeromq=4.2.5=h439df22_0
  - zlib=1.2.11=ha838bed_2
  - pip:
    - beautifulsoup4==4.6.0
    - counter==1.0.0
    - sightengine==1.4.0
    - xlrd==1.1.0
prefix: /home/slobodan/anaconda3/envs/binder_env
